[0m13:25:49.975366 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11159c050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11301f9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11301fb10>]}


============================== 13:25:49.980523 | 347ee578-b96e-4ebe-91d6-d36d4be060a7 ==============================
[0m13:25:49.980523 [info ] [MainThread]: Running with dbt=1.10.11
[0m13:25:49.981094 [debug] [MainThread]: running dbt with arguments {'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'warn_error': 'None', 'debug': 'False', 'no_print': 'None', 'log_path': 'logs', 'empty': 'None', 'quiet': 'False', 'fail_fast': 'False', 'introspect': 'True', 'invocation_command': 'dbt init ecommerce_dbt', 'profiles_dir': '/Users/hado/.dbt', 'log_cache_events': 'False', 'use_experimental_parser': 'False', 'send_anonymous_usage_stats': 'True', 'cache_selected_only': 'False', 'indirect_selection': 'eager', 'version_check': 'True', 'static_parser': 'True', 'partial_parse': 'True', 'use_colors': 'True', 'write_json': 'True', 'printer_width': '80', 'log_format': 'default'}
[0m13:25:49.998872 [debug] [MainThread]: Starter project path: /opt/anaconda3/envs/project_learning/lib/python3.13/site-packages/dbt/include/starter_project
[0m13:25:50.006757 [info ] [MainThread]: 
Your new dbt project "ecommerce_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:25:50.007185 [info ] [MainThread]: Setting up your profile.
[0m13:27:29.848171 [info ] [MainThread]: Profile ecommerce_dbt written to /Users/hado/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m13:27:29.864646 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 99.97797, "process_in_blocks": "0", "process_kernel_time": 0.225206, "process_mem_max_rss": "102912000", "process_out_blocks": "0", "process_user_time": 1.266932}
[0m13:27:29.867279 [debug] [MainThread]: Command `dbt init` succeeded at 13:27:29.866279 after 99.98 seconds
[0m13:27:29.868878 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1130bf6f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1129957f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11310c8d0>]}
[0m13:27:29.870290 [debug] [MainThread]: Flushing usage events
[0m13:27:30.581683 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:27:43.915442 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110d9c050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11281b9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11281bb10>]}


============================== 13:27:43.920878 | 1de0fdb1-d22c-44b4-9e20-16d9da342a9b ==============================
[0m13:27:43.920878 [info ] [MainThread]: Running with dbt=1.10.11
[0m13:27:43.921483 [debug] [MainThread]: running dbt with arguments {'static_parser': 'True', 'printer_width': '80', 'version_check': 'True', 'fail_fast': 'False', 'target_path': 'None', 'empty': 'None', 'use_experimental_parser': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'write_json': 'True', 'log_cache_events': 'False', 'no_print': 'None', 'partial_parse': 'True', 'use_colors': 'True', 'warn_error': 'None', 'log_format': 'default', 'cache_selected_only': 'False', 'indirect_selection': 'eager', 'profiles_dir': '/Users/hado/.dbt', 'invocation_command': 'dbt debug', 'log_path': 'logs', 'quiet': 'False', 'introspect': 'True', 'debug': 'False'}
[0m13:27:43.940404 [info ] [MainThread]: dbt version: 1.10.11
[0m13:27:43.940798 [info ] [MainThread]: python version: 3.13.5
[0m13:27:43.941060 [info ] [MainThread]: python path: /opt/anaconda3/envs/project_learning/bin/python3.13
[0m13:27:43.941309 [info ] [MainThread]: os info: macOS-10.16-x86_64-i386-64bit-Mach-O
[0m13:27:44.018110 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.snowflake'
[0m13:27:44.018641 [info ] [MainThread]: Using profiles dir at /Users/hado/.dbt
[0m13:27:44.018907 [info ] [MainThread]: Using profiles.yml file at /Users/hado/.dbt/profiles.yml
[0m13:27:44.019147 [info ] [MainThread]: Using dbt_project.yml file at /Users/hado/Desktop/Career/Coding/Data Engineer /Project/E-Commerce_Project/dbt_project.yml
[0m13:27:44.019400 [info ] [MainThread]: Configuration:
[0m13:27:44.019625 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m13:27:44.019847 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m13:27:44.020066 [info ] [MainThread]: Required dependencies:
[0m13:27:44.020367 [debug] [MainThread]: Executing "git --help"
[0m13:27:44.171947 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m13:27:44.172923 [debug] [MainThread]: STDERR: "b''"
[0m13:27:44.173265 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m13:27:44.173568 [info ] [MainThread]: Connection test skipped since no profile was found
[0m13:27:44.173974 [info ] [MainThread]: [31m2 checks failed:[0m
[0m13:27:44.174250 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "netflix_rating_project", target "dev" invalid: Runtime Error
    Could not find adapter type snowflake!


[0m13:27:44.174548 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/hado/Desktop/Career/Coding/Data Engineer /Project/E-Commerce_Project/dbt_project.yml> not found

[0m13:27:44.176564 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.34719628, "process_in_blocks": "0", "process_kernel_time": 0.383156, "process_mem_max_rss": "109965312", "process_out_blocks": "0", "process_user_time": 1.235673}
[0m13:27:44.177316 [debug] [MainThread]: Command `dbt debug` failed at 13:27:44.177025 after 0.35 seconds
[0m13:27:44.177832 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11303c3e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113048a70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112909e10>]}
[0m13:27:44.178326 [debug] [MainThread]: Flushing usage events
[0m13:27:44.528590 [debug] [MainThread]: An error was encountered while trying to flush usage events
